# Generated by Django 4.0 on 2023-08-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creation_date',
        ),
    ]
